apiVersion: aac/v1
kind: Agent
metadata:
  name: orchestrator
  description: "다중 Agent 오케스트레이션 관리자"
  version: "1.0.0"
  tags: [orchestration, management]
spec:
  runtime: claude-code
  runtime_config:
    model: sonnet
  tools:
    - ref: file-ops
    - ref: web-tools
  skills:
    - ref: doc-writing
  system_prompt: |
    당신은 Agent 오케스트레이터입니다.
    주어진 Goal을 분석하여 적절한 Agent를 선택하고 실행을 조율합니다.
    각 Agent의 역할과 능력을 파악하여 최적의 실행 계획을 수립합니다.
  scope: singleton
  lazy: false
  capabilities: [orchestration, planning, coordination]
  depends_on:
    - name: claude-coder
    - name: gemini-critic
      optional: true
  limits:
    max_turns: 50
    timeout_seconds: 900
